### PR TITLE
Able to run Viewer.py on Windows 10

### PR DESCRIPTION
**Pull request by miguelfradinho**
Quoting first commit's message:
> Issue probably comes from some shenanigans with SDL's driver on Windows 10. When loading the bitmap with pygame, the pixels had different values, what it looks like signed 32-bit integers vs what it seems to be Linux's unsigned 32-bits.

Despite very simple fix, has only been tested on Windows 10.
Behaviour of pygame might not be the same in other Windows versions

### CODE REVIEW

**Review by dgomes — COMMENTED** [review]
Extremamente ineficiente...

var = var & 0xFFFFFFFF

**Comment by miguelfradinho** [comment]
Mas isso não implicaria fazer para cada valor no array lido?
Mudar as constantes significa que só fazemos 5 operações.
Invés de estarmos a fazer o AND para cada valor do array.

**Comment by dgomes** [comment]
eu só estou a sugerir trocar a operação subtracção com 64bits ?! pela operação AND sobre 32bits...

**Comment by miguelfradinho** [comment]
Okay no subtractions this time, only bitwise operations

**Comment by dgomes** [comment]
🎉

**Pull request merged**
